### ISSUE TITLE
Look into using Netlify

### ISSUE THREAD

**Issue by LucioFranco** [amethyst/website-legacy#100]
At work we have been using Netlify to do all the website building. It is free for open source use and I think it is a good fit for our project.

**Comment by torkleyy** [comment]
https://www.getgutenberg.io/documentation/deployment/netlify/

**Comment by LucioFranco** [comment]
@torkleyy one issue with netlify is building the docs and the book both require a good amount of compute power and rust to be installed and kept up to date which I don't think netlify has.

**Comment by torkleyy** [comment]
Ah ok, just wanted to post an additional resource.

**Comment by piedoom** [comment]
I like netlify a lot, however I don't know if they would be able to build our Rust docs the way Travis can.  We also would only have one owner of the project on Netlify unless we paid for a team account.

**Comment by LucioFranco** [comment]
we would not be able to you are correct so for now I say we stay with our current strategy.
