### ISSUE TITLE
Move mdbooks install to script

### ISSUE THREAD

**Issue by LucioFranco** [amethyst/website-legacy#11]
Right now in the docs it says that you should install mdbooks before you run the script. I think we should put the install in the actual script.

**Comment by ebkalderon** [comment]
Now that the website has been successfully built with the newest script, we are free to work on this. Do you (or anyone else) want to tackle it, or should I?

**Comment by ebkalderon** [comment]
I guess I can do this while waiting for the nameservers to switch over to CloudFlare.

**Comment by LucioFranco** [comment]
This issue has been resolved with #16.
