### ISSUE TITLE
Use CloudFlare

### ISSUE THREAD

**Issue by LucioFranco** [amethyst/website-legacy#12]
I would suggest using [CloudFlare](http://cloudflare.com/). It will allow us to have free https and file caching. This could help speed up the site and also make it look more secure. It would not cost and we could do more powerful dns stuff. It would only require the domain registrar to setup nameservers that point to it. I use this for my personal site and have found that it really helps.

**Comment by ebkalderon** [comment]
I'll check out CloudFlare now and see if I can set it up.

**Comment by ebkalderon** [comment]
I've got the nameservers for `amethyst.rs` switched to CloudFlare. It may take up to 30 minutes for the rollover to complete. Ideally, we should have no downtime.

**Comment by ebkalderon** [comment]
The nameservers appear to have switched, but it hasn't propagated everywhere yet. The CloudFlare website claims it may take about 24 hours for the DNS changes to apply everywhere globally. I'll hold off on closing this issue until I can verify that it's done.

**Comment by ebkalderon** [comment]
Suddenly I'm seeing this on my browser when I navigate to https://www.amethyst.rs/. What about you guys?

![screenshot from 2016-03-23 00-12-33](https://cloud.githubusercontent.com/assets/322831/13975505/768a9eba-f08c-11e5-9f9a-6332af58300a.png)

**Comment by LucioFranco** [comment]
@ebkalderon It is still not working this morning

**Comment by ebkalderon** [comment]
@LucioFranco I'm working on it. It was working when I left Gitter at around 3 AM, but it looks like something broke overnight.

**Comment by ebkalderon** [comment]
Interesting. The WordPress version of _TWIA_ (https://blog.amethyst.rs/) works fine with CloudFlare. So the issue must be either with CloudFlare's A records or with GitHub Pages itself.

**Comment by LucioFranco** [comment]
@ebkalderon Have you been in contact with CloudFlare?

**Comment by ebkalderon** [comment]
No. I think I'll email them now, though. This is getting ridiculous.

**Comment by LucioFranco** [comment]
@ebkalderon Once we solve this issue. Will we be moving to the cobalt blog officially?

**Comment by ebkalderon** [comment]
No, there are two things I'm thinking of adding first:
1. We should display the publication date next to each post under "What's new?"
2. We need to expose the RSS feed on the website and verify it works correctly.

Do you mind opening these two issues for me while I contact CloudFlare?

**Comment by LucioFranco** [comment]
@ebkalderon Sounds good! Ill go make those two issues.

**Comment by ebkalderon** [comment]
I think the DNS record changes have resolved this issue, and HTTPS seems to work again. Let's keep this open a little while longer as we verify it works everywhere.

**Comment by LucioFranco** [comment]
I can now confirm that `https` works perfectly for me now on my school network. I think we can close this! Great work @ebkalderon !

**Comment by ebkalderon** [comment]
Awesome! Thanks for all the help. :+1:
