### ISSUE TITLE
Github menu link disappears on iPhone 5 

### ISSUE THREAD

**Issue by LucioFranco** [amethyst/website-legacy#13]
The menu item disappears. This should be an easy fix. @Aceeri you might want to tackle this.

![image](https://cloud.githubusercontent.com/assets/5758045/13972678/51c7f4a0-f060-11e5-8d67-368d0f11f036.png)

**Comment by ebkalderon** [comment]
Perhaps we could improve usability by making the menu items collapse into a hamburger button when the page width is reduced to a particular size?

**Comment by LucioFranco** [comment]
@ebkalderon This can definitely be done with bootstrap!

**Comment by LucioFranco** [comment]
#19 resolves this

**Comment by ebkalderon** [comment]
I'll open a new issue for the hamburger menu.
