### ISSUE TITLE
/doc/latest/doc/amethyst 404

### ISSUE THREAD

**Issue by robert-wallis** [amethyst/website-legacy#138]
`https://www.amethyst.rs/doc/latest/doc/amethyst` linked from https://www.amethyst.rs/doc/
and
`https://www.amethyst.rs/doc/master/doc/amethyst` linked from https://crates.io/crates/amethyst on the `documentation` link are both down.  Both of them 404.

**Comment by LucioFranco** [comment]
Thank you for reporting this! I tried it this morning and both seem to work could you verify that this is still happening?

**Comment by robert-wallis** [comment]
Looks like it’s fixed :tada:

**Comment by LucioFranco** [comment]
Awesome, thanks for verifying! 😄
