### ISSUE TITLE
TWIA post order not correct

### ISSUE THREAD

**Issue by LucioFranco** [amethyst/website-legacy#14]
![image](https://cloud.githubusercontent.com/assets/5758045/13973349/92befc72-f067-11e5-95b5-6f9aa0b9d038.png)

We want it to be the latest first not oldest first.

**Comment by LucioFranco** [comment]
This issue has been resolved with #17. I think we can close this issue.

**Comment by ebkalderon** [comment]
I agree. I think this has been resolved.
