### ISSUE TITLE
Add favicon

### ISSUE THREAD

**Issue by piedoom** [amethyst/website-legacy#148]

**Comment by Moxinilian** [comment]
This has been fixed by a recent PR.

**Comment by piedoom** [comment]
Hmm, I would recommend we don't use an [SVG since it is not well supported](https://caniuse.com/#feat=link-icon-svg).  We need an ico.

**Comment by CrackedP0t** [comment]
We could just use a PNG - that's [well-supported](url). And honestly, according to the usage tables, we really don't even need to bother with a `favicon.ico`.
Chrome [recommends](https://developers.google.com/web/fundamentals/design-and-ux/browser-customization/) a 192x192 PNG.
I'll make a PR with the changes.

**Comment by piedoom** [comment]
Cool, sounds good!
