### ISSUE TITLE
Book and API Reference 404

### ISSUE THREAD

**Issue by Worble** [amethyst/website-legacy#173]
On the [documentation page](https://www.amethyst.rs/doc/) of the site, the book and api links for both stable and latest lead to 404's.

https://www.amethyst.rs/book/latest
https://www.amethyst.rs/doc/latest/doc/amethyst
https://www.amethyst.rs/book/master
https://www.amethyst.rs/doc/master/doc/amethyst

**Comment by torkleyy** [comment]
Thank you @Worble for the report!

We had to migrate to Netlify due to certificate issues, and we're currently working on the remaining problems.

**Comment by torkleyy** [comment]
Fixed now.
