### ISSUE TITLE
Prepare for 0.11 link variants

### ISSUE THREAD

**Issue by torkleyy** [amethyst/website-legacy#186]
We are currently linking to book and docs for the latest crates.io version and for master.

For the upcoming 0.11 release, we should probably leave the documentation for 0.10 in place for some time.

## Affected files

* `generate.sh` - docs need to be built for 0.10, 0.11 and master
* `src/config.toml` - needs to store array instead of single tag
* `src/templates/doc.html` - needs to loop over the array of doc targets

## New links

We currently link to

* https://book.amethyst.rs/stable/ and
* https://docs-src.amethyst.rs/stable/amethyst/

Given that we'll have two stable releases then, I suggest to use `/0.10` and `/0.11`, while redirecting to `/0.11` for `/stable`.

**Comment by happenslol** [comment]
Heya! Quick comment on this:
The website is not built by this script anymore, but instead by a build server that listens to github webhooks. I'll transfer it to the org asap, so that we can have that discussion over there.
