### ISSUE TITLE
Show hamburger menu on narrow displays

### ISSUE THREAD

**Issue by ebkalderon** [amethyst/website-legacy#20]
Whenever the page width decreases beyond a certain threshold, the menu at the top should collapse into a [hamburger menu](http://marketblog.envato.com/wp-content/uploads/2014/11/responsive_nav_07.jpg). This would improve usability on smaller phone displays or when viewed in half-tiled browser windows.

**Comment by Aceeri** [comment]
Is this necessary? I don't love hamburger menus since they usually just hide the navigation behind a button.

**Comment by LucioFranco** [comment]
I agree with @Aceeri we do not really need a hamburger menu. If we can not press the right menu item on a small device like an iPhone 4 then maybe we should consider the hamburger menu.

**Comment by ebkalderon** [comment]
That's reasonable. I guess we can add this only if the top menu grows long enough to be a hindrance on smaller devices. For now, especially with fix #19 in place, this isn't really necessary. I'll close this issue, and we can reopen it if a need ever arises.

**Comment by Aceeri** [comment]
If we get enough links we can add a "More" dropdown for the ones that can't fit.

**Comment by ebkalderon** [comment]
I agree with you, @Aceeri.
