### ISSUE TITLE
Commit 46d6de3 breaks CSS

### ISSUE THREAD

**Issue by ebkalderon** [amethyst/website-legacy#22]
@Aceeri After switching out `./` for `/` in commit 46d6de3, the CSS on the website broke completely. Looks like it's trying to pull the CSS from `amethyst.github.io/css/main.css`, which should be `amethyst.github.io/website/css/main.css`.

See [this screencast](http://webm.land/w/A7E4/) for further explanation.

**Comment by LucioFranco** [comment]
There is a bigger issue. If we move the `post.tpl` to having `./` instead of `/` then the blog css will not work. `./` in web related stuff is not good.

**Comment by ebkalderon** [comment]
Hmm, so I'm guessing we can't make the URLs relative to `/website/` then? This might break local viewing through `http-server` I would think.

**Comment by LucioFranco** [comment]
Yeah. Maybe we can create a script to redirect to `amethyst.rs` when you go to `amethyst.github.io/website`.

**Comment by ebkalderon** [comment]
Looks like fixing the DNS records on CloudFlare (issue #12) resolves this issue.
