### ISSUE TITLE
Expose RSS feed and test that it works

### ISSUE THREAD

**Issue by LucioFranco** [amethyst/website-legacy#24]
`amethyst.rs/rss.xml`

**Comment by LucioFranco** [comment]
@ebkalderon you should probably do this as I've never worked with an RSS feed before.

**Comment by LucioFranco** [comment]
I think this issue is also dependent on [#63](https://github.com/cobalt-org/cobalt.rs/issues/63).

**Comment by LucioFranco** [comment]
I have been testing the setup. Here are some screen shots.
![image](https://cloud.githubusercontent.com/assets/5758045/14049712/a906f496-f27c-11e5-85fb-a7a70c325af3.png)

**Comment by ebkalderon** [comment]
Let's wait for the results of #33 to build and we'll test it then!

**Comment by ebkalderon** [comment]
Looks like #33 works! Thanks for the help @LucioFranco. I think we can close this.
