### ISSUE TITLE
Update Gitter Chat on website

### ISSUE THREAD

**Issue by LucioFranco** [amethyst/website-legacy#28]
Move from old Gitter to new `amethyst/general`

**Comment by ebkalderon** [comment]
Looks good! Merged.

**Comment by ebkalderon** [comment]
Let's see what happens with gitterHQ/gitter#1185, as it may impact the outcome of this issue.

**Comment by ebkalderon** [comment]
Looks like gitterHQ/gitter#1185 is just about done, and pull request #31 has been merged, so it's safe to close this issue.
