### ISSUE TITLE
Overflowing issue on mobile

### ISSUE THREAD

**Issue by Aceeri** [amethyst/website-legacy#35]
At around 478px, something starts to overflow and lets the user scroll outside the website like this:
![Overflow](http://i.imgur.com/YFGdbSP.png)

I'm not quite sure what is causing this though, but I'm either guessing something in the footer or the gitter chat.

**Comment by ebkalderon** [comment]
@Aceeri Weird, this doesn't happen on neither Firefox nor Chromium in responsive design mode. Am I doing something wrong?

![screenshot from 2016-03-27 22-35-37](https://cloud.githubusercontent.com/assets/322831/14069782/54eb22fa-f46c-11e5-9ad7-90e027efaa45.png)

**Comment by Aceeri** [comment]
I guess we can close this, I tested it on a couple other devices (Android, iPhone, and my laptop) and couldn't get it to reproduce.
