### ISSUE TITLE
Website doesn't work well with Reddit

### ISSUE THREAD

**Issue by ebkalderon** [amethyst/website-legacy#37]
When submitting a link to the Cobalt blog to a subreddit, the following things are broken that worked with the WordPress blog:
1. Thumbnail detection
2. Website title suggestions

Anyone have an idea why this is the case?

**Comment by ebkalderon** [comment]
Let's test the meta tags out and see whether #41 works as expected. If so, I'm closing this issue.

**Comment by ebkalderon** [comment]
Looks like the suggestions don't work yet. Steps to reproduce:
1. Go to "submit a new link" page on Reddit.
2. Paste link to either homepage or _TWIA_ post.
3. Click "suggest title". It will then fail, reporting "no title found".

**Comment by ebkalderon** [comment]
> Posted on Gitter at [April 2, 2016 2:37 AM](https://gitter.im/amethyst/website?at=56ff689411ea211749c41252), copied here for records

Okay, some good news and bad news I've learned during my discussions with CloudFlare. The good news: there was a slight issue with caching, and they've taken care of that. Now the `og:` tags work correctly with Facebook (albeit with [some warnings](https://developers.facebook.com/tools/debug/og/object?q=https%3A%2F%2Fwww.amethyst.rs)).

The bad news: it's still broken on Reddit. However, according to [this GitHub issue comment](https://github.com/reddit/reddit/issues/55#issuecomment-1271350), it looks like links' `og:` tags are only processed by Reddit if they appear in the first 1024 bytes of a document. Could that be the reason?

Here are the Facebook URL Debugger links I used, so you can compare them.
- [@Aceeri's](https://developers.facebook.com/tools/debug/og/object/?q=aceeri.github.io)
- [upstream](https://developers.facebook.com/tools/debug/og/object/?q=www.amethyst.rs)

**Comment by ebkalderon** [comment]
Frustratingly enough, pull request #47 still does not resolve this problem. It looks like it probably isn't a CloudFlare problem, so I'll close my ticket with them. However, I may have to contact Reddit about this problem, since they do not have a debugger utility like Facebook does.

**Update**: Created reddit/reddit#1559.

**Comment by Aceeri** [comment]
Awesome! They seemed to have solved the problem on reddit's end!

[Example of it working](https://www.reddit.com/r/amethystthumbnail)
