### ISSUE TITLE
Move site to use include tag

### ISSUE THREAD

**Issue by LucioFranco** [amethyst/website-legacy#40]
Now that `cobalt-org/liquid#25` has been merged we can move the menu to one file and use the include tag to clean up the website code.

**Edit**: Going to have to wait on this till `cobalt.rs` updates its version of `liquid-rust`.

**Comment by LucioFranco** [comment]
This will need to wait till Friday when a new release of `liquid-rust` will come out. @ebkalderon you can assign this to me and I will take care of it when they update all the crates.

**Comment by ebkalderon** [comment]
@LucioFranco Sounds great! Thanks.

**Comment by LucioFranco** [comment]
We can close this as #49 is now merged!
