### ISSUE TITLE
Rewrite all TWIA posts in Markdown

### ISSUE THREAD

**Issue by ebkalderon** [amethyst/website-legacy#5]
Right now, the _This Week in Amethyst_ newsletter is [hosted on WordPress.com](https://thisweekinamethyst.wordpress.com/). This works fine, but I'd want for us to develop the articles in the open, much like _This Week in Rust_. Thankfully, the static website generator [Cobalt.rs](https://github.com/cobalt-org/cobalt.rs) supports blog posts generated from Markdown files.

However, unlike [mdBook](https://github.com/azerupi/mdBook) which uses [pulldown-cmark](https://github.com/google/pulldown-cmark) internally, Cobalt uses [markdown.rs](https://github.com/johannhof/markdown.rs) instead, which is not as reliable nor feature-compete (no inline-style links, sometimes inconsistent output, etc). Currently, some of the _TWIA_ articles cause Cobalt to panic (see cobalt-org/cobalt.rs#58).
# Progress

| Post | Converted to Markdown? | Compiles? |
| --- | --- | --- |
| Issue 0 | Yes | Yes |
| Issue 1 | Yes | Yes |
| Issue 2 | Yes | Yes |
| Issue 3 | Yes | Yes |
| Issue 4 | Yes | Yes |
| Issue 5 | Yes | Yes |
| Issue 6 | Yes | Yes |
| Issue 7 | Yes | Yes |

**Comment by ebkalderon** [comment]
Pull request cobalt-org/cobalt.rs#64 adds pulldown-cmark support to Cobalt.rs! All blog posts build so far without any issues. However, it hasn't been merged in yet.

See the current source on the [twia-posts](https://github.com/amethyst/website/tree/twia-posts/src/_posts) branch.

**Comment by ebkalderon** [comment]
Let's see if the website looks fine once #18 is taken care of by Travis. We might be able to close this issue very soon.

**Comment by LucioFranco** [comment]
Everything looks good to me! I think we can close this issue! Good work!

**Comment by ebkalderon** [comment]
Wonderful! Issue closed.
