### ISSUE TITLE
Gitter chat button styling broken

### ISSUE THREAD

**Issue by ebkalderon** [amethyst/website-legacy#50]
After merging #47, the embedded chat button at the bottom right corner of the site ([Gitter Sidecar](https://sidecar.gitter.im/)) now has broken styling.

On Firefox:
- Web font does not load correctly
- When highlighted, color changes to green instead of to dark purple

On Chrome/Chromium:
- Web font does not load correctly
- Both normal/highlight colors are light/dark green instead of light/dark purple, respectively

**Comment by Aceeri** [comment]
I'm willing to bet this is either because of the compression or the gitter stylesheet needs to be before the main.css. Give me a moment to test this.
