### ISSUE TITLE
Images do not appear in the documentation

### ISSUE THREAD

**Issue by rookboom** [amethyst/website-legacy#95]
For example, the logo at the top of 

https://www.amethyst.rs/book/master/
 
it points to 

https://www.amethyst.rs/book/master/images/amethyst_thumb.png

 which returns 404. 

There are several other examples. Such as the image at the bottom of the first page of the Pong tutorial:

https://www.amethyst.rs/book/master/pong_tutorial/pong_tutorial_01.html

It just shows 'Step one' with no image.

**Comment by ebkalderon** [comment]
Thanks so much for the report, @rookboom! It appears that recent changes to the website have fixed these issues already. The first two links you posted no longer resolve to a 404, and the second link has been updated to https://www.amethyst.rs/book/master/pong-tutorial/pong-tutorial-01.html, and the image at the bottom now resolves correctly. Please confirm that all three image links are working now on your end.

**Comment by rookboom** [comment]
It works now. 😀
